FROM node:16 as build
WORKDIR /app
COPY frontend/package.json .
RUN npm install
COPY frontend/ ./
RUN npm run build --configuration=production

FROM nginx:alpine
COPY --from=build /app/dist/frontend /usr/share/nginx/html
EXPOSE 80